WITH DAY_DIFF AS (
SELECT O.ANIMAL_ID, DATEDIFF(O.DATETIME, I.DATETIME) AS DAY_DIFF
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
  ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY 2 DESC
LIMIT 2
)

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
JOIN DAY_DIFF D
  ON O.ANIMAL_ID = D.ANIMAL_ID