-- 식당별 평균점수 테이블 저장

WITH
AVG_SCORE AS (
SELECT REST_ID, 
       AVG(REVIEW_SCORE) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID
)

-- 조인하여 조건부 조회

SELECT A.REST_ID, 
       A.REST_NAME,
       A.FOOD_TYPE,
       A.FAVORITES,
       A.ADDRESS,
       ROUND(B.SCORE,2) AS SCORE
FROM REST_INFO A
JOIN AVG_SCORE B
ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC
