SELECT EXTRACT(HOUR FROM DATETIME) AS HOUR,
       COUNT(EXTRACT(HOUR FROM DATETIME)) AS COUNT
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM DATETIME) BETWEEN '09:00' AND '19:59'
GROUP BY EXTRACT(HOUR FROM DATETIME)
ORDER BY HOUR