SELECT A.ITEM_ID, 
       A.ITEM_NAME, 
       A.RARITY
FROM ITEM_INFO A
JOIN (SELECT DISTINCT T.ITEM_ID, T.PARENT_ITEM_ID, I.RARITY
      FROM ITEM_TREE T
      INNER JOIN ITEM_INFO I
      ON T.PARENT_ITEM_ID = I.ITEM_ID
      WHERE I.RARITY = 'RARE') B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC