SELECT BOOK_ID, 
       AUTHOR_NAME, 
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK t1, AUTHOR t2
WHERE t1.AUTHOR_ID = t2.AUTHOR_ID
  AND t1.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
